### PR TITLE
add back styling in action menu areas, fix silent update fail issue

### LINKED ISSUE #77: Update does not complete when entry has a dependency

### PR DESCRIPTION
**Pull request by mahos**
- nullable tag area got fixed
- buttons now all styled
- adjust input area styling to match across

image

- resolve update fail bug by correcting the tinyInt field. Fixes #77

### CODE REVIEW

File: src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx [hunk 1]
```diff
@@ -238,8 +238,8 @@ class UpdateTuple extends React.Component<{
               <div>
                 <p>Are you sure you want to submit form to update this entry?</p>
                 <div className="actionButtons">
-                  <input className="submitButton" type="submit" value="Submit"/>
-                  <button className="cancelButton" onClick={() => {this.setState({dependencies: []}); this.props.clearEntrySelection();}}>Cancel</button>
+                  <input className="confirmActionButton update" type="submit" value="Update"/>
```
Comment (Synicix) [inline src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx:241]: Can CSS name have spaces?

**Review by guzman-raphael — APPROVED** [review]

File: src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx (hunk 1 above)
Comment (mahos) [reply src/Components/MainTableView/UpdateTuple/UpdateTuple.tsx:241]: yeah that's me adding a second class `update` on top of the first class `confirmActionButton` for that button
